using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class IDEAS : MonoBehaviour {

	// GAME MENU STARTS WITH ROOM OF PERSON WITH PONYTAIL AND GLASSES SITTING IN
    // FRONT OF A WINDOWS XP COMPUTER. WHEN THE USER PRESSES PLAY, THE CAMERA
    // ZOOMS IN TO THE MONITOR.

    // FILES POPUP ON THE MONITOR AS THE DATA IS RECOVED, BUT IF THE MONITOR
    // FILLS UP, YOU LOSE!

    // YOUR JOB IS TO SORT THE FILES INTO DIFFERENT FOLDERS, BUT SOME FILES ARE
    // MALICIOUS WORMS, AND WILL CREATE A TON OF "TRASH" FILES WHICH YOU NEED TO
    // CLEAR OUT BEFORE YOU CAN RECOVER OTHER FILES.
}
